In [71]:
import scipy as sp
import numpy as np

In [72]:
#Example 1:

In [73]:
A = np.array([[1, 1, -1], [3, -1, 1], [1, -3, 2]], dtype=float)
A

array([[ 1.,  1., -1.],
       [ 3., -1.,  1.],
       [ 1., -3.,  2.]])

In [74]:
b = np.array([[0], [4], [1.02]], dtype=float)
b

array([[0.  ],
       [4.  ],
       [1.02]])

In [75]:
np.linalg.solve(A, b)

array([[1.  ],
       [1.98],
       [2.98]])

In [76]:
#Example 2:

In [77]:
C = np.array([[1, 1], [1.0001, 1]], dtype=float)
d = np.array([[2], [2.0002]], dtype=float)

In [78]:
np.linalg.solve(C, d)

array([[2.],
       [0.]])

In [79]:
np.linalg.cond(A)

np.float64(13.786035815258492)

In [80]:
np.linalg.cond(C, p='fro')

np.float64(40002.00009999336)